#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

// Copy public directory to dist
const publicDir = path.join(__dirname, 'public');
const distDir = path.join(__dirname, 'dist');

// Create dist directory
if (!fs.existsSync(distDir)) {
  fs.mkdirSync(distDir, { recursive: true });
}

// Copy all files from public to dist
function copyDir(src, dst) {
  fs.readdirSync(src).forEach(file => {
    const srcFile = path.join(src, file);
    const dstFile = path.join(dst, file);
    if (fs.statSync(srcFile).isDirectory()) {
      if (!fs.existsSync(dstFile)) fs.mkdirSync(dstFile);
      copyDir(srcFile, dstFile);
    } else {
      fs.copyFileSync(srcFile, dstFile);
    }
  });
}

copyDir(publicDir, distDir);

// ---------------------------------------------------------------- config ---
// Credentials resolve through lib/env.js, which also reads .env.local, so the
// file Supabase's dashboard tells you to create works without being copied
// anywhere. A deployment's own environment always wins over that file.
const { loadSupabaseEnv, assertPublishableKey } = require('./lib/env.js');
const { supabaseUrl, supabaseAnonKey, urlFrom, keyFrom } = loadSupabaseEnv();

assertPublishableKey(supabaseAnonKey);
if (supabaseUrl && !/^https:\/\/[a-z0-9-]+\.supabase\.(co|in)$/.test(supabaseUrl)) {
  console.warn(`! ${urlFrom} does not look like a Supabase project URL: ${supabaseUrl}`);
}
if (supabaseUrl && !supabaseAnonKey) {
  throw new Error('A Supabase URL is set but no key. Set SUPABASE_ANON_KEY or NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY.');
}
if (supabaseAnonKey && !supabaseUrl) {
  throw new Error('A Supabase key is set but no URL. Set SUPABASE_URL or NEXT_PUBLIC_SUPABASE_URL.');
}

// A build stamp so a maintainer can tell exactly what is deployed. Vercel
// exposes the commit SHA; locally we fall back to "dev".
const pkg = JSON.parse(fs.readFileSync(path.join(__dirname, 'package.json'), 'utf8'));
const commit = (process.env.VERCEL_GIT_COMMIT_SHA || '').slice(0, 7) || 'dev';
fs.writeFileSync(
  path.join(distDir, 'config.js'),
  `/* Generated by build.js — do not edit. */\nwindow.FURNISHAR_CONFIG = ${JSON.stringify({
    supabaseUrl,
    supabaseAnonKey,
    version: pkg.version,
    commit,
    builtAt: new Date().toISOString()
  }, null, 2)};\n`
);
console.log(supabaseUrl
  ? `✓ Build complete: public/ → dist/ (Supabase: ${new URL(supabaseUrl).host}, key from ${keyFrom})`
  : '✓ Build complete: public/ → dist/ (bundled catalogue — no Supabase URL found)');
