#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

// Copy public directory to dist
const publicDir = path.join(__dirname, 'public');
const distDir = path.join(__dirname, 'dist');

// Create dist directory
if (!fs.existsSync(distDir)) {
  fs.mkdirSync(distDir, { recursive: true });
}

// Copy all files from public to dist
function copyDir(src, dst) {
  fs.readdirSync(src).forEach(file => {
    const srcFile = path.join(src, file);
    const dstFile = path.join(dst, file);
    if (fs.statSync(srcFile).isDirectory()) {
      if (!fs.existsSync(dstFile)) fs.mkdirSync(dstFile);
      copyDir(srcFile, dstFile);
    } else {
      fs.copyFileSync(srcFile, dstFile);
    }
  });
}

copyDir(publicDir, distDir);

// Runtime config comes from the deployment's environment, never from the repo.
// Without these variables the app keeps its bundled-catalogue behaviour.
const supabaseUrl = process.env.SUPABASE_URL || '';
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY || '';
if (supabaseAnonKey.includes('service_role')) {
  throw new Error('SUPABASE_ANON_KEY looks like a service role key. That key must never reach the browser.');
}
fs.writeFileSync(
  path.join(distDir, 'config.js'),
  `/* Generated by build.js — do not edit. */\nwindow.FURNISHAR_CONFIG = ${JSON.stringify({ supabaseUrl, supabaseAnonKey }, null, 2)};\n`
);
console.log(supabaseUrl
  ? `✓ Build complete: public/ copied to dist/ (Supabase backend: ${new URL(supabaseUrl).host})`
  : '✓ Build complete: public/ copied to dist/ (bundled catalogue — no SUPABASE_URL set)');
